### PR TITLE
PAL fix and CoAP libraries for Matter SVE event

### PR DESCRIPTION
**Pull request by suveshpratapa**
* Fix a platform bug affecting Thread certification and update openthread certification libraries
* Support for certification libraries with CoAP enabled

### CODE REVIEW

**Review by romacdon — APPROVED** [review]
LGTM

**Review by lmnotran — APPROVED** [review]

**Comment by lmnotran** [comment]
@suveshpratapa can you fix the build failures?

**Comment by suveshpratapa** [comment]
> @suveshpratapa can you fix the build failures?

The build failure is strange to me since the PAL code is the same as what's on [ot-efr32/main](https://github.com/openthread/ot-efr32)

By the way, I also see the same build failure on the HEAD of our `matter_sve` branch: https://github.com/SiliconLabs/ot-efr32/commits/matter_sve

It shouldn't affect the Matter SVE program at the moment since the failure is when generating an RCP application.

**Comment by suveshpratapa** [comment]
> @suveshpratapa can you fix the build failures?

Fixed after merging your PR.  Please re-review.

**Review by romacdon — APPROVED** [review]
Still LGTM

**Comment by lmnotran** [comment]
Still LGTM!

**Review by lmnotran — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
