### PR TITLE
Correct README files

### PR DESCRIPTION
**Pull request by silabs-WayneW**
1- Correct bin path.
2- Adjust the position of the git submodule update --init command.

### CODE REVIEW

**Comment by silabs-WayneW** [comment]
Run ./script/bootstrap will have the following errors information, so need to run git submodule update --init first.
------------------------------------------------------------------------
pi@raspberrypi:~ $ cd ot-efr32/
pi@raspberrypi:~/ot-efr32 $ ./script/bootstrap
++ dirname ./script/bootstrap
+ ./script/../openthread/script/bootstrap
./script/bootstrap: line 32: ./script/../openthread/script/bootstrap: No such file or directory
pi@raspberrypi:~/ot-efr32 $
------------------------------------------------------------------------

**Comment by romacdon** [comment]
@silabs-WayneW thanks for creating this PR.  It looks good to me so I will approve.  I will also add @lmnotran as reviewer.  I do want to mention, and perhaps you know this already, https://github.com/SiliconLabs/ot-efr32 is not the repo that the community should be using.  https://github.com/openthread/ot-efr32 is the repo that they should be using.  So once this PR is approved and merged I'd like to ask that you then create a PR to https://github.com/openthread/ot-efr32.  Thanks for finding this and opening the PR.

In fact, now that I think about it, I think this PR conflicts with the changes @lmnotran has in this PR https://github.com/openthread/ot-efr32/pull/14 to the other repo.

**Comment by romacdon** [comment]
@silabs-WayneW after discussing with @lmnotran we believe the best approach is for you to open the PR to https://github.com/openthread/ot-efr32 instead of this repo.  Can you close this PR and create a new one to that repo?  Thanks.

**Comment by lmnotran** [comment]
@silabs-WayneW I think your changes are covered by openthread/ot-efr32#14. Please double check to make sure I didn't miss anything. If I did, feel free to make a PR to `main` on the original `ot-efr32` repo. PRs for this fork are pretty much only used for staging

**Pull request closed without merging**
