### PR TITLE
Fix sleepy demo README link for flashing binaries

### PR DESCRIPTION
**Pull request by bertoldi-silabs**

### CODE REVIEW

**Comment by romacdon** [comment]
@bertoldi-silabs The change looks good but I see you are trying to merge to main.  We do not push to siliconlabs/ot-efr32 main as it is an exact clone of whats in openthread/ot-efr32 main.  Instead we create a staging branch and open a PR against the staging branch for review then when approved merge to the staging branch and then open subsequent PR to openthread/ot-efr32.

**Comment by lmnotran** [comment]
@romacdon this can be merged directly to openthread/ot-efr32:main. We only do staging branches for larger PRs. I agree though, this PR needs to target `openthread/ot-efr32:main`

**Comment by romacdon** [comment]
> @romacdon this can be merged directly to openthread/ot-efr32:main. We only do staging branches for larger PRs. I agree though, this PR needs to target `openthread/ot-efr32:main`

@lmnotran openthread/ot-efr32 main but not not siliconlabs/ot-efr32 main. Am I missing something?  We never merge directly to siliconlabs/ot-efr32 main. That would have our main have a fix that is not in openthread/ot-efr32 main and we don't want that.

**Comment by bertoldi-silabs** [comment]
> > @romacdon this can be merged directly to openthread/ot-efr32:main. We only do staging branches for larger PRs. I agree though, this PR needs to target `openthread/ot-efr32:main`
> 
> @lmnotran openthread/ot-efr32 main but not not siliconlabs/ot-efr32 main. Am I missing something? We never merge directly to siliconlabs/ot-efr32 main. That would have our main have a fix that is not in openthread/ot-efr32 main and we don't want that.

I think I just made a mistake about which main to merge with. When pushing to siliconlabs/ot-efr32, I just expected that the target of the pull request would also be siliconlabs/ot-efr32 when I was told that the target branch was main. I just didn't consider that it would be for openthread/ot-efr32:main instead. My bad, I'll get that changed over...

**Comment by lmnotran** [comment]
@romacdon - You're correct. We never target `SiliconLabs/ot-efr32:main` and we only target `openthread/ot-efr32:main`. I was just meaning to say that using a staging branch would be unnecessary as this was such a small change.

**Comment by bertoldi-silabs** [comment]
This PR should target openthread/ot-efr32:main instead of SiliconLabs/ot-efr32:main.

A new PR has been opened at https://github.com/openthread/ot-efr32/pull/365 to merge these changes in to the appropriate target.

**Comment by romacdon** [comment]
> @romacdon - You're correct. We never target `SiliconLabs/ot-efr32:main` and we only target `openthread/ot-efr32:main`. I was just meaning to say that using a staging branch would be unnecessary as this was such a small change.

Yup, completely agree.

**Pull request closed without merging**
